version: '3'
services:
  web:
    image: nginx:latest
    ports:
      – "80:80"
    volumes:
      – ./web:/usr/share/nginx/html
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      – db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
volumes:
  db-data:
