jobs:
    – name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    – name: Run Docker Compose
      export POSTGRES_USER=postgres
      export POSTGRES_PASSWORD=postgres
      run: docker-compose up -d
